# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Coating_Cycle_Customizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
STYLE GUIDE:
(Colors in HSB)

Bright: 310 25 90
Grey: 280 25 75
Dark: 250 75 50
"""


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QWidget, QVBoxLayout
from PyQt5.QtCore import Qt
import CycleEditor
from CycleEditor import CoatCycle
import csv
import os
import Firmware as firmware
# WARNING: Deleting cycles does not remove them from the backend
# NOTE: Use itemAt() to access widgets positionally (can later use to access items in lists)
# TODO: Use json file for name configurations

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, ActiveCycle: CoatCycle):
        self.active_cycle = ActiveCycle
        # Setting up base for app
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.setWindowIcon(QtGui.QIcon("prism_icon.jpg"))
        MainWindow.resize(1024, 600)
        MainWindow.setWindowTitle("PRISM LbL")
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)

        # Central widget will be stacked to allow for multiple screens
        self.stackedWidget = QtWidgets.QStackedWidget(MainWindow)
        self.stackedWidget.setObjectName("stackedWidget")
        self.setupMainMenu()
        self.setupCycleEditor()
        self.setupSettings()
        self.stackedWidget.setCurrentIndex(0)
        MainWindow.setCentralWidget(self.stackedWidget)

    def setupCycleEditor(self):
        self.widget_CycleEditor = QtWidgets.QWidget()
        self.widget_CycleEditor.setObjectName("widget_CycleEditor")
        font = QtGui.QFont()

        self.createLabel(self.widget_CycleEditor, "Nozzle Path: ", [220, 500, 100, 30], font)
        self.selectPathing = QtWidgets.QComboBox(self.widget_CycleEditor)
        self.selectPathing.setGeometry(QtCore.QRect(325, 500, 180, 30))
        self.selectPathing.setObjectName("selectCoating")
        self.selectPathing.addItems(self.active_cycle.nozzle_paths)

        self.label_numberOfCycles = self.createLabel(self.widget_CycleEditor, "Number of Cycles: ", [10, 500, 150, 30], font)
        self.lineEdit_numberOfCycles = QtWidgets.QLineEdit(self.widget_CycleEditor)
        self.lineEdit_numberOfCycles.setGeometry(QtCore.QRect(160, 500, 50, 30))

        self.button_addStep = self.createButton(self.widget_CycleEditor, "Add Step", [644, 160, 331, 31], self.addStepWidget)


        self.selectCoating = QtWidgets.QComboBox(self.widget_CycleEditor)
        self.selectCoating.setGeometry(QtCore.QRect(790, 50, 181, 31))
        self.selectCoating.setObjectName("selectCoating")
        self.selectCoating.addItem("Reservoir 1")
        self.selectCoating.addItem("Reservoir 2")
        self.selectCoating.addItem("Reservoir 3")
        self.selectCoating.addItem("Reservoir 4")

        self.lineEdit_numberOfCoats = QtWidgets.QLineEdit(self.widget_CycleEditor)
        self.lineEdit_numberOfCoats.setGeometry(QtCore.QRect(860, 100, 111, 31))
        font.setPointSize(16)
        self.lineEdit_numberOfCoats.setFont(font)
        self.lineEdit_numberOfCoats.setText("")
        self.lineEdit_numberOfCoats.setObjectName("lineEdit_numberOfCoats")

        font.setPointSize(11)
        self.label_selectCoating = self.createLabel(self.widget_CycleEditor, "Coating Solution: ", [640, 60, 131, 31], font)
        self.label_numberOfCoats = self.createLabel(self.widget_CycleEditor, "Number of Coats: ", [640, 110, 191, 31], font)

        self.Coating_Step_List = QtWidgets.QFrame(self.widget_CycleEditor)
        self.Coating_Step_List.setGeometry(QtCore.QRect(0, 0, 630, 500))
        self.Coating_Step_List.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Coating_Step_List.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Coating_Step_List.setObjectName("Coating_Step_List")
        self.Coating_Step_List_Layout = QVBoxLayout(self.Coating_Step_List)

        self.button_Home_CycleEditor = self.createButton(self.widget_CycleEditor, "Return Home", 
                                                         [640, 460, 150, 40], self.clickedHome)
        self.button_SaveCycleEditor = self.createButton(self.widget_CycleEditor, "Save", 
                                                        [810, 460, 150, 40], self.clickedSaveCycleEditor)
        self.button_StartCycle = self.createButton(self.widget_CycleEditor, "Start Cycle", 
                                                   [640, 400, 320, 50], self.clickedStartCycle)
        self.button_LoadCycle = self.createButton(self.widget_CycleEditor, "Load Saved Cycle",
                                                  [640, 340, 320, 50], self.clickedLoadCycle)

        self.stackedWidget.addWidget(self.widget_CycleEditor)

    def setupMainMenu(self):
        self.widget_MainMenu = QtWidgets.QWidget()
        self.widget_MainMenu.setObjectName("widget_MainMenu")
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Title = QtWidgets.QLabel(self.widget_MainMenu)
        self.label_Title.setGeometry(QtCore.QRect(312, 60, 400, 60))
        self.label_Title.setObjectName("label_Title")
        self.label_Title.setText("PRISM LbL")
        self.label_Title.setAlignment(Qt.AlignmentFlag.AlignHCenter)
        self.label_Title.setFont(font)

        self.button_Start = self.createButton(self.widget_MainMenu, "Start", [412, 300, 200, 40], self.clickedStart)
        self.button_Settings = self.createButton(self.widget_MainMenu, "Settings", [412, 400, 200, 40], self.clickedSettings)

        self.stackedWidget.addWidget(self.widget_MainMenu)
    
    def setupSettings(self):
        font = QtGui.QFont()
        font.setPointSize(20)
        self.widget_Settings = QWidget()
        self.widget_Settings.setObjectName("widget_Settings")

        self.label_Settings = self.createLabel(self.widget_Settings, "Settings", [412, 20, 200, 40], 
                                               font, Qt.AlignmentFlag.AlignHCenter)
        font.setPointSize(11)

        self.label_Reservoir1 = self.createLabel(self.widget_Settings, "Name of Reservoir 1:", [50, 150, 200, 30], font)
        self.lineEdit_Reservoir1 = QtWidgets.QLineEdit(self.widget_Settings)
        self.lineEdit_Reservoir1.setGeometry(QtCore.QRect(250, 150, 250, 30))

        self.label_Reservoir2 = self.createLabel(self.widget_Settings, "Name of Reservoir 2:", [50, 190, 200, 30], font)
        self.lineEdit_Reservoir2 = QtWidgets.QLineEdit(self.widget_Settings)
        self.lineEdit_Reservoir2.setGeometry(QtCore.QRect(250, 190, 250, 30))

        self.label_Reservoir3 = self.createLabel(self.widget_Settings, "Name of Reservoir 3:", [50, 230, 200, 30], font)
        self.lineEdit_Reservoir3 = QtWidgets.QLineEdit(self.widget_Settings)
        self.lineEdit_Reservoir3.setGeometry(QtCore.QRect(250, 230, 250, 30))

        self.label_Reservoir4 = self.createLabel(self.widget_Settings, "Name of Reservoir 4:", [50, 270, 200, 30], font)
        self.lineEdit_Reservoir4 = QtWidgets.QLineEdit(self.widget_Settings)
        self.lineEdit_Reservoir4.setGeometry(QtCore.QRect(250, 270, 250, 30))

        self.button_Home_Settings = self.createButton(self.widget_Settings, "Return Home", [640, 450, 150, 40], self.clickedHome)
        self.button_SaveSettings = self.createButton(self.widget_Settings, "Save", [810, 450, 150, 40], self.clickedSaveSettings)
        self.button_LoadSettings = self.createButton(self.widget_Settings, "Load", [810, 400, 150, 40], self.clickedLoadSettings)

        self.clickedLoadSettings() # Loads the reservoir names

        self.stackedWidget.addWidget(self.widget_Settings)

    def createButton(self, widget: QWidget, text: str, geometry: list[int], connected_method):
        object = QtWidgets.QPushButton(widget)
        object.setGeometry(QtCore.QRect(geometry[0], geometry[1], geometry[2], geometry[3]))
        object.setText(text)
        object.setObjectName("button_" + text)
        object.clicked.connect(connected_method)
        return object
    
    def createLabel(self, widget: QWidget, text:str, geometry:list[int], font, alignment=Qt.AlignmentFlag.AlignLeft):
        object = QLabel(widget)
        object.setGeometry(QtCore.QRect(geometry[0], geometry[1], geometry[2], geometry[3]))
        object.setText(text)
        object.setObjectName("label_" + text)
        object.setAlignment(alignment)
        object.setFont(font)
        return object
    
    def loadStepWidget(self, coat_count, reservoir_index):
        self.unit_step = QWidget()
        self.unit_step.setGeometry(QtCore.QRect(10, 10, 611, 51))
        self.unit_step.setObjectName("unit_step")
        self.unit_step.setStyleSheet("background-color: #E5A1DA")
        font = QtGui.QFont()

        self.unit_step.setProperty("reservoir_index", reservoir_index)
        self.unit_step.setProperty("coat_count", coat_count)

        self.selectCoating.setCurrentIndex(reservoir_index)
        coating_solution = self.selectCoating.currentText()

        self.label_Solution = self.createLabel(self.unit_step, f"Res {reservoir_index} - {coating_solution}", 
                                               [18, 9, 191, 31], font)
        self.label_Solution.setAutoFillBackground(True)

        self.label_Coats = self.createLabel(self.unit_step, f"Coats: {coat_count}", [238, 10, 121, 31], font)
        self.label_Coats.setAutoFillBackground(True)

        self.button_delete = self.createButton(self.unit_step, "Delete", [510, 13, 75, 31], self.unit_step.deleteLater)

        self.Coating_Step_List_Layout.addWidget(self.unit_step)

    def addStepWidget(self):
        try:
            coat_count = int(self.lineEdit_numberOfCoats.text())
        except ValueError:
            print("ERROR Incorrect value entered in Number of Coats, integers only")
            return
        coating_solution = self.selectCoating.currentText()
        reservoir_index = self.selectCoating.currentIndex()
        font = QtGui.QFont()
        # initializing coating step widget and assigning information unique to it
        self.unit_step = QWidget()
        self.unit_step.setGeometry(QtCore.QRect(10, 10, 611, 51))
        self.unit_step.setObjectName("unit_step")
        self.unit_step.setStyleSheet("background-color: #E5A1DA")
        self.unit_step.setProperty("reservoir_index", reservoir_index)
        self.unit_step.setProperty("coat_count", coat_count)
        # adding display information to the widget
        self.label_Solution = self.createLabel(self.unit_step, f"Res {reservoir_index} - {coating_solution}", 
                                               [18, 9, 191, 31], font)
        self.label_Solution.setAutoFillBackground(True)
        self.label_Coats = self.createLabel(self.unit_step, f"Coats: {coat_count}", [238, 10, 121, 31], font)
        self.label_Coats.setAutoFillBackground(True)
        self.button_delete = self.createButton(self.unit_step, "Delete", [510, 13, 75, 31], font, self.unit_step.deleteLater)

        self.Coating_Step_List_Layout.addWidget(self.unit_step)
    
    def gatherCycleSettings(self):
        try:
            cycle_count = int(self.lineEdit_numberOfCycles.text())
        except ValueError:
            print("Incorrect value in number of cycles")
            return 0
        nozzle_path = self.selectPathing.currentText()
        step_count = self.Coating_Step_List_Layout.count()
        arr_coat_count = [0] * step_count # initializes coat count array with correct size
        arr_reservoir = [0] * step_count # initializes reservoir array with correct size
        for step in range(step_count): # grabs data from each coating step widget
            active_step = self.Coating_Step_List_Layout.itemAt(step).widget() # pulls up the coating step widget for this step
            coating_count = active_step.property("coat_count") # gets the coat count for this step
            arr_coat_count[step] = coating_count # puts data in array for consolidation

            reservoir_index = active_step.property("reservoir_index") # gets the reservoir for this step
            arr_reservoir[step] = reservoir_index # puts data in array for consolidation

            print("Step #{0} : Coat count = {1} : Reservoir index = {2}".format(step, coating_count, reservoir_index))

        self.createCoatVector(step_count, cycle_count, arr_coat_count, arr_reservoir, nozzle_path)

    def createCoatVector(self, step_count, cycle_count, arr_coat_count, arr_reservoir, nozzle_path):
        self.coat_vector = [step_count, cycle_count, arr_coat_count, arr_reservoir, nozzle_path]
        self.loadCoatVector()

    def updateCycleEditor(self):
        self.gatherCycleSettings()
        self.active_cycle.coat_vector = self.coat_vector
        self.active_cycle.loadCoatVector()

    def loadCoatVector(self):
        self.step_count = self.coat_vector[2][0]
        self.cycle_count = self.coat_vector[2][1]
        self.arr_reservoir = self.coat_vector[0]
        self.arr_coat_count = self.coat_vector[1]
        self.nozzle_path = self.coat_vector[3]

    def clickedHome(self):
        self.stackedWidget.setCurrentIndex(0)
        self.button_SaveSettings.setText("Save")
        print("Clicked Home\n")

    def clickedStart(self):
        self.stackedWidget.setCurrentIndex(1)
        print("Clicked Start\n")

    def clickedSettings(self):
        self.stackedWidget.setCurrentIndex(2)
        print("Clicked Settings\n")
    
    def clickedSaveSettings(self):
        print("Clicked Save Settings\n")
        self.button_SaveSettings.setText("Saved!")
        text_res1 = self.lineEdit_Reservoir1.text()
        text_res2 = self.lineEdit_Reservoir2.text()
        text_res3 = self.lineEdit_Reservoir3.text()
        text_res4 = self.lineEdit_Reservoir4.text()
        self.selectCoating.setItemText(0, text_res1)
        self.selectCoating.setItemText(1, text_res2)
        self.selectCoating.setItemText(2, text_res3)
        self.selectCoating.setItemText(3, text_res4)
        save_vector = [text_res1, text_res2, text_res3, text_res4]
        with open("SavedSettings.csv", "w", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(save_vector)
            print("Settings data saved to SavedSettings.csv")
    
    def clickedLoadSettings(self):
        str_line = []
        with open("SavedSettings.csv", "r") as file:
            content = csv.reader(file)
            str_line = [s for s in content]
            print(str_line)
        
        text_res1 = str_line[0][0]
        text_res2 = str_line[0][1]
        text_res3 = str_line[0][2]
        text_res4 = str_line[0][3]
        
        self.lineEdit_Reservoir1.setText(text_res1)
        self.lineEdit_Reservoir2.setText(text_res2)
        self.lineEdit_Reservoir3.setText(text_res3)
        self.lineEdit_Reservoir4.setText(text_res4)

        self.selectCoating.setItemText(0, text_res1)
        self.selectCoating.setItemText(1, text_res2)
        self.selectCoating.setItemText(2, text_res3)
        self.selectCoating.setItemText(3, text_res4)
    
    def clickedSaveCycleEditor(self):
        self.updateCycleEditor()
        self.active_cycle.loadCoatVector()
        self.active_cycle.generateSaveFile()

    def clickedStartCycle(self):
        print("Beginning coating cycle...\n")
        self.updateCycleEditor()
        self.active_cycle.loadCoatVector()
        self.active_cycle.executeCycle()

    def clickedLoadCycle(self):
        self.active_cycle.loadSaveFile()
        self.coat_vector = self.active_cycle.coat_vector
        self.loadCoatVector()
        for step in range(self.step_count):
            self.loadStepWidget(self.arr_coat_count[step], self.arr_reservoir[step])
        self.lineEdit_numberOfCycles.setText(str(self.cycle_count))
        self.selectPathing.setCurrentText(self.nozzle_path)
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ActiveCycle = CoatCycle()
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, ActiveCycle)
    MainWindow.show()
    sys.exit(app.exec_())
