# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Coating_Cycle_Customizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QWidget, QVBoxLayout


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1022, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.Add_Coating_Step = QtWidgets.QFrame(self.frame)
        self.Add_Coating_Step.setGeometry(QtCore.QRect(640, 10, 361, 231))
        self.Add_Coating_Step.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Add_Coating_Step.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Add_Coating_Step.setObjectName("Add_Coating_Step")

        self.button_addStep = QtWidgets.QPushButton(self.Add_Coating_Step)
        self.button_addStep.setGeometry(QtCore.QRect(4, 150, 331, 31))
        self.button_addStep.setObjectName("button_addStep")
        self.button_addStep.clicked.connect(self.addStepWidget)

        self.selectCoating = QtWidgets.QComboBox(self.Add_Coating_Step)
        self.selectCoating.setGeometry(QtCore.QRect(150, 40, 181, 31))
        self.selectCoating.setObjectName("selectCoating")
        self.selectCoating.addItem("")
        self.selectCoating.addItem("")
        self.selectCoating.addItem("")

        self.lineEdit_numberOfCoats = QtWidgets.QLineEdit(self.Add_Coating_Step)
        self.lineEdit_numberOfCoats.setGeometry(QtCore.QRect(220, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_numberOfCoats.setFont(font)
        self.lineEdit_numberOfCoats.setText("")
        self.lineEdit_numberOfCoats.setObjectName("lineEdit_numberOfCoats")

        self.label_selectCoating = QtWidgets.QLabel(self.Add_Coating_Step)
        self.label_selectCoating.setGeometry(QtCore.QRect(0, 40, 131, 31))
        self.label_selectCoating.setObjectName("label_selectCoating")

        self.label_numberOfCoats = QtWidgets.QLabel(self.Add_Coating_Step)
        self.label_numberOfCoats.setGeometry(QtCore.QRect(0, 90, 191, 31))
        self.label_numberOfCoats.setObjectName("label_numberOfCoats")

        self.Coating_Step_List = QtWidgets.QFrame(self.frame)
        self.Coating_Step_List.setGeometry(QtCore.QRect(0, 0, 631, 501))
        self.Coating_Step_List.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Coating_Step_List.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Coating_Step_List.setObjectName("Coating_Step_List")
        self.Coating_Step_List_Layout = QVBoxLayout(self.Coating_Step_List)

        
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_addStep.setText(_translate("MainWindow", "Add Step"))
        self.selectCoating.setItemText(0, _translate("MainWindow", "Solution 1"))
        self.selectCoating.setItemText(1, _translate("MainWindow", "Solution 2"))
        self.selectCoating.setItemText(2, _translate("MainWindow", "Solution 3"))
        self.label_selectCoating.setText(_translate("MainWindow", "Coating Solution:"))
        self.label_numberOfCoats.setText(_translate("MainWindow", "Number of Coats:"))
    
    def addStepWidget(self):
        self.unit_step = QWidget()
        self.unit_step.setGeometry(QtCore.QRect(10, 10, 611, 51))
        self.unit_step.setObjectName("unit_step")

        number_of_coats = int(self.lineEdit_numberOfCoats.text())
        coating_solution = self.selectCoating.currentText()

        self.label_Solution = QLabel(self.unit_step)
        self.label_Solution.setGeometry(QtCore.QRect(18, 9, 191, 31))
        self.label_Solution.setAutoFillBackground(True)
        self.label_Solution.setObjectName("label_Solution")
        self.label_Solution.setText(coating_solution)

        self.label_Coats = QtWidgets.QLabel(self.unit_step)
        self.label_Coats.setGeometry(QtCore.QRect(238, 10, 121, 31))
        self.label_Coats.setAutoFillBackground(True)
        self.label_Coats.setObjectName("label_Coats")
        self.label_Coats.setText("Coats: {}".format(number_of_coats))

        self.button_delete = QtWidgets.QPushButton(self.unit_step)
        self.button_delete.setGeometry(QtCore.QRect(510, 13, 75, 31))
        self.button_delete.setObjectName("button_delete")
        self.button_delete.setText("Delete")
        self.button_delete.clicked.connect(self.unit_step.deleteLater)

        self.Coating_Step_List_Layout.addWidget(self.unit_step)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
